import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { saira, sairaCondensed } from "./fonts";
import "./tailwind.css";
import Footer from "../components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" className="scroll-smooth bg-zinc-900">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${saira.variable} ${sairaCondensed.variable} antialiased min-h-screen bg-black text-base-content font-saira`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
